# Generated by Django 3.2.7 on 2021-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Üerschrift', max_length=200)),
                ('position', models.IntegerField(blank=True, default=0, help_text='Sortierfeld')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
    ]
