# Generated by Django 3.2.7 on 2021-09-14 09:00

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
